<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64;ARM64</Platforms>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AssemblyName>GestureSign-Uninstall</AssemblyName>
    <RootNamespace>GestureSign.Uninstaller</RootNamespace>
    <ApplicationIcon>..\..\GestureSign.WinUI\Assets\logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <LangVersion>latest</LangVersion>
    <Version>18.1.9.0</Version>
    <AssemblyVersion>18.1.9.0</AssemblyVersion>
    <FileVersion>18.1.9.0</FileVersion>
  </PropertyGroup>
</Project>
