<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AssemblyName>GestureSign.Common</AssemblyName>
    <RootNamespace>GestureSign.Common</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GestureSign.PointPatterns\GestureSign.PointPatterns.csproj" />
    <ProjectReference Include="..\ManagedWinapi\ManagedWinapi.csproj" />
    <ProjectReference Include="..\WindowsInput\WindowsInput.csproj" />
  </ItemGroup>
</Project>
